### ISSUE TITLE
Retain Cycles

### ISSUE THREAD

**Issue by otymartin** [instacart/TrueTime.swift#36] opened 2017-09-11 19:25 UTC
@msanders 
A quick view of the memory debugger shows that this library leaks so much memory
![screen shot 2017-09-11 at 3 23 53 pm](https://user-images.githubusercontent.com/2222881/30292744-46d74e7c-9705-11e7-9476-7e1510a34de4.png)
![screen shot 2017-09-11 at 3 23 58 pm](https://user-images.githubusercontent.com/2222881/30292748-48d2ca08-9705-11e7-94b8-1d46826a010a.png)

**Comment by msanders** [comment] 2017-09-11 21:28
@otymartin: Thanks for reporting. Was having trouble reproducing but seeing a similar issue now when testing against recurrent timeouts / bad network conditions. Is this related to the scenario you were seeing this in?

**Comment by msanders** [comment] 2017-09-12 22:14
@otymartin: This should be fixed now on master and will be included in 4.1.4. Let me know if you run into anything else!

**Closed by msanders** 2017-09-12 22:14 UTC

**Comment by otymartin** [comment] 2017-09-12 22:39
@msanders 
Excuse the late response. Dont know how to answer your question.
Reference TrueTime like this in all my scenarious where I may need to make a network call depended on server time eg. performing transactions. And right before using it, as a safety check I always use guard statement to check if `now()` exists or `fetchInNeed()` if `now()` is nil.

Ill check the new master and report back with any other memory issues.
```swift
 fileprivate var now: Date? {
        return TrueTimeClient.sharedInstance.referenceTime?.now()
    }
...
guard let now = self.now else {
            TrueTimeClient.sharedInstance.fetchIfNeeded()
            return
        }
```

**Comment by otymartin** [comment] 2017-10-21 18:53
hey @msanders truetime is still leaking quite abit.
This from memory debugger are all truetime related.
From Xcode 9, Swift 4, iOS 10 target.
![screen shot 2017-10-17 at 10 45 31 am](https://user-images.githubusercontent.com/2222881/31854989-841cf3c0-b66f-11e7-9f79-7e0e0272e28c.png)

**Comment by miketsprague** [comment] 2018-04-20 10:06
This is a bit strange.  I'm seeing the same behavior in my app, specifically running this causes 10 leaks according to xcode:
```swift
        for i in (0..<10) {
            TrueTimeClient.sharedInstance.fetchIfNeeded()
        }
```

But I'm unable to reproduce the memory leak in the example project.  Could there be a retain cycle in NTPConnection.swift's `close`?  This is calling `lockQueue.async(execute: work)`, where `work` has a strong reference to `self`.  Does the `lockQueue` have a strong reference to the work closure (and we have a strong reference to `lockQueue`)?

Specifying `[self weak]` in the capture list for that closure "fixed" the issue in my project, but I'm unsure as to why I'm unable to reproduce it in the example project.

Additional reference, I'm using commit `8aadebabe2590d6ab295c390df5bbc109b346348` via cocoapods in my project.

**Comment by sangios** [comment] 2019-02-13 03:26
I faced the issue as @msanders reported

**Comment by sangios** [comment] 2019-02-13 03:30
The issue still happens.

**Comment by santanaNogueira** [comment] 2022-02-16 15:17
Did anyone find a solution to this issue? Thanks in advance!
